# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dvm < Formula
  desc "DevOpsMaestro (dvm) - CLI tool for managing development workspaces"
  homepage "https://github.com/rmkohlman/devopsmaestro"
  version "0.3.0"
  license "GPL-3.0"

  on_macos do
    on_arm do
      url "https://github.com/rmkohlman/devopsmaestro/releases/download/v0.3.0/devopsmaestro_0.3.0_darwin_arm64.tar.gz"
      sha256 "8bf9787a511ee66d1ccdd34b860aad054a194abd9ddab8f7c6b4d6492db8fcd0"

      def install
        bin.install "dvm"
        generate_completions_from_executable(bin/"dvm", "completion")
      end
    end
  end

  test do
    system "#{bin}/dvm", "version"
  end
end
