# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Maestrovault < Formula
  desc "MaestroVault — a macOS-first, developer-focused secrets management tool with CLI, TUI, and vim motions"
  homepage "https://github.com/rmkohlman/MaestroVault"
  version "0.7.0"
  license "Apache-2.0"
  depends_on :macos

  url "https://github.com/rmkohlman/MaestroVault/releases/download/v0.7.0/mav_0.7.0_darwin_all.tar.gz"
  sha256 "2dae61b5c37be63d6747e71db0ac60c5703ed14998f65b91c61b8868973ff997"

  define_method(:install) do
    bin.install "mav"
    generate_completions_from_executable(bin/"mav", "completion")
  end

  test do
    system "#{bin}/mav", "version"
  end
end
