# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Maestrovault < Formula
  desc "MaestroVault — a macOS-first, developer-focused secrets management tool with CLI, TUI, and vim motions"
  homepage "https://github.com/rmkohlman/MaestroVault"
  version "0.10.4"
  license "Apache-2.0"
  depends_on :macos

  url "https://github.com/rmkohlman/MaestroVault/releases/download/v0.10.4/mav_0.10.4_darwin_all.tar.gz"
  sha256 "6a4ce2a153f69c6052f192135ffbe08027b7abad84515a9fed82f31e7efee9a7"

  define_method(:install) do
    bin.install "mav"
    generate_completions_from_executable(bin/"mav", "completion")
  end

  test do
    system "#{bin}/mav", "version"
  end
end
